name: deploy
on:
  push:
    branches:
      - annotations
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install bikeshed
    - run: echo "::add-matcher::.github/problem-matcher.json"
    - run: bikeshed --print plain --die-on everything spec --line-numbers | sed 's/^LINE /ERROR:index.bs:/'
